### ISSUE TITLE
[pathfinder 2e] Choosing an action applies to all actions in all

### ISSUE THREAD

**Issue by bushvin** [dyslexic-charactersheets/lib-charactersheets#24]
When selecting how many actions an activity takes causes all icons on the same page to become the selected type.

**How to reproduce:**
1. Create a Pathfinder 2e character sheet with additional actions
1. Go to the page containing Actions (_Actions_, _Skill Actions_, _Focus Actions_)
1. Click any action icon and select an activity.

All icons in _Actions_, _Skill Actions_, _Focus Actions_ are changed to the selected activity.

Tested with _Barbarian_, _Magus_ and _Sorcerer_ character sheet.

**Comment by marcus-downing** [comment]
I thought I already fixed this one a few weeks ago. Is it still a problem now?

**Comment by bushvin** [comment]
I created 2 new characters just yesterday.

maybe you didn’t push from github to your website?

**Comment by marcus-downing** [comment]
It seems fine to me. Can you send me the file?

**Comment by bushvin** [comment]
Here you go: [link](https://wolk.elaba.net/s/WF8CLnenMCkpJNi)

**Comment by marcus-downing** [comment]
I'm very confused. That file works fine for me. I select an action, it changes that action.

What browser are you using?
Can you pull up the inspector / dev tools (probably F12) and see if anything appears in the console?
If all else fails, would you be willing to jump on a Discord or Zoom call to debug this together?

**Comment by bushvin** [comment]
Apologies for my late response.

I have shared a folder for your convenience:
[https://wolk.elaba.net/s/GbbNZGg9yDaRcgQ](https://wolk.elaba.net/s/GbbNZGg9yDaRcgQ)

There is a screencast for both firefox and chromium and the html which I used to generate the screencast.
the html was generated after raising this issue here.

I am experiencing the same issue running Firefox 110.0 (daily driver) and Chromium 111.0.5563.64 (backup)

Something does happen when clicking the action icon, but not the first time. From the second time on it throws the below error:
```javascript
Uncaught TypeError: document.getElementById(...) is null
    showActionMenu file:///home/XXXXXXXXXX/Abbaccus/Abbaccus, Sorcerer.html:3079
    EventListener.handleEvent* file:///home/XXXXXXXXXX/Abbaccus/Abbaccus, Sorcerer.html:3128
[Abbaccus, Sorcerer.html:3079:12](file:///home/XXXXXXXXXX/Abbaccus/Abbaccus,%20Sorcerer.html)
    showActionMenu file:///home/XXXXXXXXXX/Abbaccus/Abbaccus, Sorcerer.html:3079
    (Async: EventListener.handleEvent)
    <anonymous> file:///home/XXXXXXXXXX/Abbaccus/Abbaccus, Sorcerer.html:3128
```
I've also included a screencast for this on firefox.

Let me know if you would like more. discord or zoom is fine, my timezone is GMT+1, which isn't too far off yours, if I'm correct.

**Comment by marcus-downing** [comment]
I think I see the confusion. I didn't realise you were looking at the Actions page, so I was clicking the actions on the Character and Combat pages (skill actions, focus actions etc) and they all worked.

**Comment by marcus-downing** [comment]
You did say that. I just failed to read it.

**Comment by marcus-downing** [comment]
Hello,
I believe the fix for this is live now. Can you confirm if it's fixed?
