### ISSUE TITLE
[PF2] Kingmaker untranslatable

### ISSUE THREAD

**Issue by christof337** [dyslexic-charactersheets/lib-charactersheets#25]
The pf2 Kingmaker entries doesn't show UP in the translation plateform.
I would love to be able to translate it !

**Comment by christof337** [comment]
Btw I downloaded the file and translated the entries manually 😅
When they'll be on the platform I'll copy them!

**Comment by marcus-downing** [comment]
I've just updated the translation master, so you should now be able to translate them.

Thank you.

**Comment by christof337** [comment]
Should be good, thanks !

**Comment by christof337** [comment]
Hi, can you please update the website with my translations please? 🙏 @marcus-downing
