### ISSUE TITLE
Possibilité de choisir le nombre de pages de sorts à inclure

### ISSUE THREAD

**Issue by dcpc007** [dyslexic-charactersheets/lib-charactersheets#4]
Comme il est difficile d'éditer des pdf, dupliquer numériquement la page de sorts à noter est compliqué (et payant en plus en général).

Est-il possible de rajouter par ex une liste déroulante pour prévoir X pages de sorts dans le pdf généré ?

**Comment by marcus-downing** [comment]
Why do you need more copies of the same page? Can't you just print it several times?
